#define MyAppName "CK Stem Splitter"
#define MyAppVersion "0.6.1"
#define MyAppPublisher "Commercial Kings"
#define MyAppURL "https://commercialkings.com"

[Setup]
AppId={{9A98B982-3A8D-4A89-A7DF-FF2762A4E0F1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={commonpf}\{#MyAppPublisher}\{#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputDir=..\dist
OutputBaseFilename=CK-Stem-Splitter-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
Uninstallable=yes
CreateUninstallRegKey=yes
SetupLogging=yes

[Components]
Name: "vst3"; Description: "VST3 Plugin"; Types: full compact custom
Name: "vst2"; Description: "VST2 Plugin"; Types: full custom
Name: "aax"; Description: "AAX Plugin (Pro Tools)"; Types: full custom
Name: "lv2"; Description: "LV2 Plugin"; Types: full custom
Name: "standalone"; Description: "Standalone Application"; Types: full custom

[Files]
; --- 1. PLUGINS ---

; VST3
Source: "..\staging\CK Stem Splitter.vst3\*"; DestDir: "{commonpf}\Common Files\VST3\CK Stem Splitter.vst3"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: vst3

; VST2
Source: "..\staging\CK Stem Splitter.dll"; DestDir: "{commonpf}\Common Files\VST2"; Flags: ignoreversion; Components: vst2

; AAX
Source: "..\staging\CK Stem Splitter.aaxplugin\*"; DestDir: "{commonpf}\Common Files\Avid\Audio\Plug-Ins\CK Stem Splitter.aaxplugin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: aax

; LV2
Source: "..\staging\CK Stem Splitter.lv2\*"; DestDir: "{commonpf}\Common Files\LV2\CK Stem Splitter.lv2"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: lv2

; Standalone
Source: "..\staging\CK Stem Splitter.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: standalone


; --- 2. PYTHON ENGINE AND IL MODEL  ---

; executable file generated by PyInstaller
Source: "..\staging\engine\ckstem-engine\ckstem-engine.exe"; DestDir: "{commonappdata}\{#MyAppPublisher}\{#MyAppName}\engine"; Flags: ignoreversion recursesubdirs createallsubdirs

; ONNX Model
Source: "..\staging\engine\models\*"; DestDir: "{commonappdata}\{#MyAppPublisher}\{#MyAppName}\engine\models"; Flags: ignoreversion

[Dirs]
Name: "{commonappdata}\{#MyAppPublisher}\{#MyAppName}\engine"
Name: "{commonappdata}\{#MyAppPublisher}\{#MyAppName}\engine\models"

[Run]
Filename: "{cmd}"; Parameters: "/C echo CK Stem Splitter installed successfully."; Flags: runhidden nowait
